// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameState.proto

package org.robocup_logistics.llsf_msgs;

public final class GameStateProtos {
  private GameStateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameStateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .llsf_msgs.Time game_time = 1;
    boolean hasGameTime();
    org.robocup_logistics.llsf_msgs.TimeProtos.Time getGameTime();
    org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder getGameTimeOrBuilder();
    
    // required .llsf_msgs.GameState.State state = 3;
    boolean hasState();
    org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State getState();
    
    // required .llsf_msgs.GameState.Phase phase = 4;
    boolean hasPhase();
    org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase getPhase();
    
    // optional uint32 points = 5;
    boolean hasPoints();
    int getPoints();
    
    // optional string team = 6;
    boolean hasTeam();
    String getTeam();
    
    // optional .llsf_msgs.GameState.RefBoxMode refbox_mode = 7 [default = STANDALONE];
    boolean hasRefboxMode();
    org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode getRefboxMode();
  }
  public static final class GameState extends
      com.google.protobuf.GeneratedMessage
      implements GameStateOrBuilder {
    // Use GameState.newBuilder() to construct.
    private GameState(Builder builder) {
      super(builder);
    }
    private GameState(boolean noInit) {}
    
    private static final GameState defaultInstance;
    public static GameState getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameState getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_GameState_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_GameState_fieldAccessorTable;
    }
    
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      COMP_ID(0, 2000),
      MSG_TYPE(1, 20),
      ;
      
      public static final int COMP_ID_VALUE = 2000;
      public static final int MSG_TYPE_VALUE = 20;
      
      
      public final int getNumber() { return value; }
      
      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 20: return MSG_TYPE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CompType[] VALUES = {
        COMP_ID, MSG_TYPE, 
      };
      
      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.GameState.CompType)
    }
    
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      INIT(0, 0),
      WAIT_START(1, 1),
      RUNNING(2, 2),
      PAUSED(3, 3),
      ;
      
      public static final int INIT_VALUE = 0;
      public static final int WAIT_START_VALUE = 1;
      public static final int RUNNING_VALUE = 2;
      public static final int PAUSED_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static State valueOf(int value) {
        switch (value) {
          case 0: return INIT;
          case 1: return WAIT_START;
          case 2: return RUNNING;
          case 3: return PAUSED;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<State>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final State[] VALUES = {
        INIT, WAIT_START, RUNNING, PAUSED, 
      };
      
      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private State(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.GameState.State)
    }
    
    public enum Phase
        implements com.google.protobuf.ProtocolMessageEnum {
      PRE_GAME(0, 0),
      SETUP(1, 10),
      EXPLORATION(2, 20),
      PRODUCTION(3, 30),
      POST_GAME(4, 40),
      OPEN_CHALLENGE(5, 1000),
      NAVIGATION_CHALLENGE(6, 1001),
      WHACK_A_MOLE_CHALLENGE(7, 1002),
      ;
      
      public static final int PRE_GAME_VALUE = 0;
      public static final int SETUP_VALUE = 10;
      public static final int EXPLORATION_VALUE = 20;
      public static final int PRODUCTION_VALUE = 30;
      public static final int POST_GAME_VALUE = 40;
      public static final int OPEN_CHALLENGE_VALUE = 1000;
      public static final int NAVIGATION_CHALLENGE_VALUE = 1001;
      public static final int WHACK_A_MOLE_CHALLENGE_VALUE = 1002;
      
      
      public final int getNumber() { return value; }
      
      public static Phase valueOf(int value) {
        switch (value) {
          case 0: return PRE_GAME;
          case 10: return SETUP;
          case 20: return EXPLORATION;
          case 30: return PRODUCTION;
          case 40: return POST_GAME;
          case 1000: return OPEN_CHALLENGE;
          case 1001: return NAVIGATION_CHALLENGE;
          case 1002: return WHACK_A_MOLE_CHALLENGE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Phase>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Phase>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Phase>() {
              public Phase findValueByNumber(int number) {
                return Phase.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.getDescriptor().getEnumTypes().get(2);
      }
      
      private static final Phase[] VALUES = {
        PRE_GAME, SETUP, EXPLORATION, PRODUCTION, POST_GAME, OPEN_CHALLENGE, NAVIGATION_CHALLENGE, WHACK_A_MOLE_CHALLENGE, 
      };
      
      public static Phase valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Phase(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.GameState.Phase)
    }
    
    public enum RefBoxMode
        implements com.google.protobuf.ProtocolMessageEnum {
      STANDALONE(0, 0),
      MASTER(1, 1),
      SLAVE(2, 2),
      ;
      
      public static final int STANDALONE_VALUE = 0;
      public static final int MASTER_VALUE = 1;
      public static final int SLAVE_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static RefBoxMode valueOf(int value) {
        switch (value) {
          case 0: return STANDALONE;
          case 1: return MASTER;
          case 2: return SLAVE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<RefBoxMode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RefBoxMode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RefBoxMode>() {
              public RefBoxMode findValueByNumber(int number) {
                return RefBoxMode.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.getDescriptor().getEnumTypes().get(3);
      }
      
      private static final RefBoxMode[] VALUES = {
        STANDALONE, MASTER, SLAVE, 
      };
      
      public static RefBoxMode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private RefBoxMode(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.GameState.RefBoxMode)
    }
    
    private int bitField0_;
    // required .llsf_msgs.Time game_time = 1;
    public static final int GAME_TIME_FIELD_NUMBER = 1;
    private org.robocup_logistics.llsf_msgs.TimeProtos.Time gameTime_;
    public boolean hasGameTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.robocup_logistics.llsf_msgs.TimeProtos.Time getGameTime() {
      return gameTime_;
    }
    public org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder getGameTimeOrBuilder() {
      return gameTime_;
    }
    
    // required .llsf_msgs.GameState.State state = 3;
    public static final int STATE_FIELD_NUMBER = 3;
    private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State getState() {
      return state_;
    }
    
    // required .llsf_msgs.GameState.Phase phase = 4;
    public static final int PHASE_FIELD_NUMBER = 4;
    private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase phase_;
    public boolean hasPhase() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase getPhase() {
      return phase_;
    }
    
    // optional uint32 points = 5;
    public static final int POINTS_FIELD_NUMBER = 5;
    private int points_;
    public boolean hasPoints() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getPoints() {
      return points_;
    }
    
    // optional string team = 6;
    public static final int TEAM_FIELD_NUMBER = 6;
    private java.lang.Object team_;
    public boolean hasTeam() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getTeam() {
      java.lang.Object ref = team_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          team_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTeamBytes() {
      java.lang.Object ref = team_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        team_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .llsf_msgs.GameState.RefBoxMode refbox_mode = 7 [default = STANDALONE];
    public static final int REFBOX_MODE_FIELD_NUMBER = 7;
    private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode refboxMode_;
    public boolean hasRefboxMode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode getRefboxMode() {
      return refboxMode_;
    }
    
    private void initFields() {
      gameTime_ = org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance();
      state_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State.INIT;
      phase_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase.PRE_GAME;
      points_ = 0;
      team_ = "";
      refboxMode_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode.STANDALONE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasGameTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhase()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getGameTime().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, gameTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(3, state_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(4, phase_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(5, points_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getTeamBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(7, refboxMode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, gameTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, state_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, phase_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, points_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTeamBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, refboxMode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.GameState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.GameState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.GameState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.GameState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.GameState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.GameState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.GameState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.GameState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.GameState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.GameState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.GameStateProtos.GameState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.GameStateProtos.GameStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_GameState_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_GameState_fieldAccessorTable;
      }
      
      // Construct using org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGameTimeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (gameTimeBuilder_ == null) {
          gameTime_ = org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance();
        } else {
          gameTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State.INIT;
        bitField0_ = (bitField0_ & ~0x00000002);
        phase_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase.PRE_GAME;
        bitField0_ = (bitField0_ & ~0x00000004);
        points_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        team_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        refboxMode_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode.STANDALONE;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.getDescriptor();
      }
      
      public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.getDefaultInstance();
      }
      
      public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState build() {
        org.robocup_logistics.llsf_msgs.GameStateProtos.GameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.robocup_logistics.llsf_msgs.GameStateProtos.GameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState buildPartial() {
        org.robocup_logistics.llsf_msgs.GameStateProtos.GameState result = new org.robocup_logistics.llsf_msgs.GameStateProtos.GameState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (gameTimeBuilder_ == null) {
          result.gameTime_ = gameTime_;
        } else {
          result.gameTime_ = gameTimeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.phase_ = phase_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.points_ = points_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.team_ = team_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.refboxMode_ = refboxMode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.GameStateProtos.GameState) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.GameStateProtos.GameState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.GameStateProtos.GameState other) {
        if (other == org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.getDefaultInstance()) return this;
        if (other.hasGameTime()) {
          mergeGameTime(other.getGameTime());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasPhase()) {
          setPhase(other.getPhase());
        }
        if (other.hasPoints()) {
          setPoints(other.getPoints());
        }
        if (other.hasTeam()) {
          setTeam(other.getTeam());
        }
        if (other.hasRefboxMode()) {
          setRefboxMode(other.getRefboxMode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasGameTime()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        if (!hasPhase()) {
          
          return false;
        }
        if (!getGameTime().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder subBuilder = org.robocup_logistics.llsf_msgs.TimeProtos.Time.newBuilder();
              if (hasGameTime()) {
                subBuilder.mergeFrom(getGameTime());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGameTime(subBuilder.buildPartial());
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State value = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                state_ = value;
              }
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase value = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                phase_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              points_ = input.readUInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              team_ = input.readBytes();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode value = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                refboxMode_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .llsf_msgs.Time game_time = 1;
      private org.robocup_logistics.llsf_msgs.TimeProtos.Time gameTime_ = org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.robocup_logistics.llsf_msgs.TimeProtos.Time, org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder, org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder> gameTimeBuilder_;
      public boolean hasGameTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.robocup_logistics.llsf_msgs.TimeProtos.Time getGameTime() {
        if (gameTimeBuilder_ == null) {
          return gameTime_;
        } else {
          return gameTimeBuilder_.getMessage();
        }
      }
      public Builder setGameTime(org.robocup_logistics.llsf_msgs.TimeProtos.Time value) {
        if (gameTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gameTime_ = value;
          onChanged();
        } else {
          gameTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setGameTime(
          org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder builderForValue) {
        if (gameTimeBuilder_ == null) {
          gameTime_ = builderForValue.build();
          onChanged();
        } else {
          gameTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeGameTime(org.robocup_logistics.llsf_msgs.TimeProtos.Time value) {
        if (gameTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              gameTime_ != org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance()) {
            gameTime_ =
              org.robocup_logistics.llsf_msgs.TimeProtos.Time.newBuilder(gameTime_).mergeFrom(value).buildPartial();
          } else {
            gameTime_ = value;
          }
          onChanged();
        } else {
          gameTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearGameTime() {
        if (gameTimeBuilder_ == null) {
          gameTime_ = org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance();
          onChanged();
        } else {
          gameTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder getGameTimeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getGameTimeFieldBuilder().getBuilder();
      }
      public org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder getGameTimeOrBuilder() {
        if (gameTimeBuilder_ != null) {
          return gameTimeBuilder_.getMessageOrBuilder();
        } else {
          return gameTime_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.robocup_logistics.llsf_msgs.TimeProtos.Time, org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder, org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder> 
          getGameTimeFieldBuilder() {
        if (gameTimeBuilder_ == null) {
          gameTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.robocup_logistics.llsf_msgs.TimeProtos.Time, org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder, org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder>(
                  gameTime_,
                  getParentForChildren(),
                  isClean());
          gameTime_ = null;
        }
        return gameTimeBuilder_;
      }
      
      // required .llsf_msgs.GameState.State state = 3;
      private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State state_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State.INIT;
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State getState() {
        return state_;
      }
      public Builder setState(org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State.INIT;
        onChanged();
        return this;
      }
      
      // required .llsf_msgs.GameState.Phase phase = 4;
      private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase phase_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase.PRE_GAME;
      public boolean hasPhase() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase getPhase() {
        return phase_;
      }
      public Builder setPhase(org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        phase_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhase() {
        bitField0_ = (bitField0_ & ~0x00000004);
        phase_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase.PRE_GAME;
        onChanged();
        return this;
      }
      
      // optional uint32 points = 5;
      private int points_ ;
      public boolean hasPoints() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getPoints() {
        return points_;
      }
      public Builder setPoints(int value) {
        bitField0_ |= 0x00000008;
        points_ = value;
        onChanged();
        return this;
      }
      public Builder clearPoints() {
        bitField0_ = (bitField0_ & ~0x00000008);
        points_ = 0;
        onChanged();
        return this;
      }
      
      // optional string team = 6;
      private java.lang.Object team_ = "";
      public boolean hasTeam() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getTeam() {
        java.lang.Object ref = team_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          team_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTeam(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        team_ = value;
        onChanged();
        return this;
      }
      public Builder clearTeam() {
        bitField0_ = (bitField0_ & ~0x00000010);
        team_ = getDefaultInstance().getTeam();
        onChanged();
        return this;
      }
      void setTeam(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        team_ = value;
        onChanged();
      }
      
      // optional .llsf_msgs.GameState.RefBoxMode refbox_mode = 7 [default = STANDALONE];
      private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode refboxMode_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode.STANDALONE;
      public boolean hasRefboxMode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode getRefboxMode() {
        return refboxMode_;
      }
      public Builder setRefboxMode(org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        refboxMode_ = value;
        onChanged();
        return this;
      }
      public Builder clearRefboxMode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        refboxMode_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.RefBoxMode.STANDALONE;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:llsf_msgs.GameState)
    }
    
    static {
      defaultInstance = new GameState(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:llsf_msgs.GameState)
  }
  
  public interface SetGameStateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .llsf_msgs.GameState.State state = 1;
    boolean hasState();
    org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State getState();
  }
  public static final class SetGameState extends
      com.google.protobuf.GeneratedMessage
      implements SetGameStateOrBuilder {
    // Use SetGameState.newBuilder() to construct.
    private SetGameState(Builder builder) {
      super(builder);
    }
    private SetGameState(boolean noInit) {}
    
    private static final SetGameState defaultInstance;
    public static SetGameState getDefaultInstance() {
      return defaultInstance;
    }
    
    public SetGameState getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_SetGameState_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_SetGameState_fieldAccessorTable;
    }
    
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      COMP_ID(0, 2000),
      MSG_TYPE(1, 21),
      ;
      
      public static final int COMP_ID_VALUE = 2000;
      public static final int MSG_TYPE_VALUE = 21;
      
      
      public final int getNumber() { return value; }
      
      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 21: return MSG_TYPE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CompType[] VALUES = {
        COMP_ID, MSG_TYPE, 
      };
      
      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.SetGameState.CompType)
    }
    
    private int bitField0_;
    // required .llsf_msgs.GameState.State state = 1;
    public static final int STATE_FIELD_NUMBER = 1;
    private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State getState() {
      return state_;
    }
    
    private void initFields() {
      state_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State.INIT;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, state_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_SetGameState_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_SetGameState_fieldAccessorTable;
      }
      
      // Construct using org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        state_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State.INIT;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState.getDescriptor();
      }
      
      public org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState.getDefaultInstance();
      }
      
      public org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState build() {
        org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState buildPartial() {
        org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState result = new org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState other) {
        if (other == org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasState()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State value = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                state_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .llsf_msgs.GameState.State state = 1;
      private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State state_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State.INIT;
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State getState() {
        return state_;
      }
      public Builder setState(org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.State.INIT;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:llsf_msgs.SetGameState)
    }
    
    static {
      defaultInstance = new SetGameState(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:llsf_msgs.SetGameState)
  }
  
  public interface SetGamePhaseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .llsf_msgs.GameState.Phase phase = 1;
    boolean hasPhase();
    org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase getPhase();
  }
  public static final class SetGamePhase extends
      com.google.protobuf.GeneratedMessage
      implements SetGamePhaseOrBuilder {
    // Use SetGamePhase.newBuilder() to construct.
    private SetGamePhase(Builder builder) {
      super(builder);
    }
    private SetGamePhase(boolean noInit) {}
    
    private static final SetGamePhase defaultInstance;
    public static SetGamePhase getDefaultInstance() {
      return defaultInstance;
    }
    
    public SetGamePhase getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_SetGamePhase_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_SetGamePhase_fieldAccessorTable;
    }
    
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      COMP_ID(0, 2000),
      MSG_TYPE(1, 22),
      ;
      
      public static final int COMP_ID_VALUE = 2000;
      public static final int MSG_TYPE_VALUE = 22;
      
      
      public final int getNumber() { return value; }
      
      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 22: return MSG_TYPE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CompType[] VALUES = {
        COMP_ID, MSG_TYPE, 
      };
      
      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.SetGamePhase.CompType)
    }
    
    private int bitField0_;
    // required .llsf_msgs.GameState.Phase phase = 1;
    public static final int PHASE_FIELD_NUMBER = 1;
    private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase phase_;
    public boolean hasPhase() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase getPhase() {
      return phase_;
    }
    
    private void initFields() {
      phase_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase.PRE_GAME;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPhase()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, phase_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, phase_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_SetGamePhase_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.internal_static_llsf_msgs_SetGamePhase_fieldAccessorTable;
      }
      
      // Construct using org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        phase_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase.PRE_GAME;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase.getDescriptor();
      }
      
      public org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase.getDefaultInstance();
      }
      
      public org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase build() {
        org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase buildPartial() {
        org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase result = new org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.phase_ = phase_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase other) {
        if (other == org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase.getDefaultInstance()) return this;
        if (other.hasPhase()) {
          setPhase(other.getPhase());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPhase()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase value = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                phase_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .llsf_msgs.GameState.Phase phase = 1;
      private org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase phase_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase.PRE_GAME;
      public boolean hasPhase() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase getPhase() {
        return phase_;
      }
      public Builder setPhase(org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        phase_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhase() {
        bitField0_ = (bitField0_ & ~0x00000001);
        phase_ = org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Phase.PRE_GAME;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:llsf_msgs.SetGamePhase)
    }
    
    static {
      defaultInstance = new SetGamePhase(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:llsf_msgs.SetGamePhase)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_GameState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_GameState_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_SetGameState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_SetGameState_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_SetGamePhase_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_SetGamePhase_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017GameState.proto\022\tllsf_msgs\032\nTime.proto" +
      "\"\236\004\n\tGameState\022\"\n\tgame_time\030\001 \002(\0132\017.llsf" +
      "_msgs.Time\022)\n\005state\030\003 \002(\0162\032.llsf_msgs.Ga" +
      "meState.State\022)\n\005phase\030\004 \002(\0162\032.llsf_msgs" +
      ".GameState.Phase\022\016\n\006points\030\005 \001(\r\022\014\n\004team" +
      "\030\006 \001(\t\022@\n\013refbox_mode\030\007 \001(\0162\037.llsf_msgs." +
      "GameState.RefBoxMode:\nSTANDALONE\"&\n\010Comp" +
      "Type\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYPE\020\024\":\n\005Stat" +
      "e\022\010\n\004INIT\020\000\022\016\n\nWAIT_START\020\001\022\013\n\007RUNNING\020\002" +
      "\022\n\n\006PAUSED\020\003\"\235\001\n\005Phase\022\014\n\010PRE_GAME\020\000\022\t\n\005",
      "SETUP\020\n\022\017\n\013EXPLORATION\020\024\022\016\n\nPRODUCTION\020\036" +
      "\022\r\n\tPOST_GAME\020(\022\023\n\016OPEN_CHALLENGE\020\350\007\022\031\n\024" +
      "NAVIGATION_CHALLENGE\020\351\007\022\033\n\026WHACK_A_MOLE_" +
      "CHALLENGE\020\352\007\"3\n\nRefBoxMode\022\016\n\nSTANDALONE" +
      "\020\000\022\n\n\006MASTER\020\001\022\t\n\005SLAVE\020\002\"a\n\014SetGameStat" +
      "e\022)\n\005state\030\001 \002(\0162\032.llsf_msgs.GameState.S" +
      "tate\"&\n\010CompType\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TY" +
      "PE\020\025\"a\n\014SetGamePhase\022)\n\005phase\030\001 \002(\0162\032.ll" +
      "sf_msgs.GameState.Phase\"&\n\010CompType\022\014\n\007C" +
      "OMP_ID\020\320\017\022\014\n\010MSG_TYPE\020\026B2\n\037org.robocup_l",
      "ogistics.llsf_msgsB\017GameStateProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_llsf_msgs_GameState_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_llsf_msgs_GameState_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_GameState_descriptor,
              new java.lang.String[] { "GameTime", "State", "Phase", "Points", "Team", "RefboxMode", },
              org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.class,
              org.robocup_logistics.llsf_msgs.GameStateProtos.GameState.Builder.class);
          internal_static_llsf_msgs_SetGameState_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_llsf_msgs_SetGameState_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_SetGameState_descriptor,
              new java.lang.String[] { "State", },
              org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState.class,
              org.robocup_logistics.llsf_msgs.GameStateProtos.SetGameState.Builder.class);
          internal_static_llsf_msgs_SetGamePhase_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_llsf_msgs_SetGamePhase_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_SetGamePhase_descriptor,
              new java.lang.String[] { "Phase", },
              org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase.class,
              org.robocup_logistics.llsf_msgs.GameStateProtos.SetGamePhase.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robocup_logistics.llsf_msgs.TimeProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
