// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MachineReport.proto

package org.robocup_logistics.llsf_msgs;

public final class MachineReportProtos {
  private MachineReportProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MachineReportEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required string type = 2;
    boolean hasType();
    String getType();
  }
  public static final class MachineReportEntry extends
      com.google.protobuf.GeneratedMessage
      implements MachineReportEntryOrBuilder {
    // Use MachineReportEntry.newBuilder() to construct.
    private MachineReportEntry(Builder builder) {
      super(builder);
    }
    private MachineReportEntry(boolean noInit) {}
    
    private static final MachineReportEntry defaultInstance;
    public static MachineReportEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public MachineReportEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReportEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReportEntry_fieldAccessorTable;
    }
    
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      COMP_ID(0, 2000),
      MSG_TYPE(1, 60),
      ;
      
      public static final int COMP_ID_VALUE = 2000;
      public static final int MSG_TYPE_VALUE = 60;
      
      
      public final int getNumber() { return value; }
      
      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 60: return MSG_TYPE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CompType[] VALUES = {
        COMP_ID, MSG_TYPE, 
      };
      
      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.MachineReportEntry.CompType)
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReportEntry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReportEntry_fieldAccessorTable;
      }
      
      // Construct using org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.getDescriptor();
      }
      
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.getDefaultInstance();
      }
      
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry build() {
        org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry buildPartial() {
        org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry result = new org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry other) {
        if (other == org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              type_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required string type = 2;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:llsf_msgs.MachineReportEntry)
    }
    
    static {
      defaultInstance = new MachineReportEntry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:llsf_msgs.MachineReportEntry)
  }
  
  public interface MachineReportOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .llsf_msgs.MachineReportEntry machines = 1;
    java.util.List<org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry> 
        getMachinesList();
    org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry getMachines(int index);
    int getMachinesCount();
    java.util.List<? extends org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntryOrBuilder> 
        getMachinesOrBuilderList();
    org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntryOrBuilder getMachinesOrBuilder(
        int index);
  }
  public static final class MachineReport extends
      com.google.protobuf.GeneratedMessage
      implements MachineReportOrBuilder {
    // Use MachineReport.newBuilder() to construct.
    private MachineReport(Builder builder) {
      super(builder);
    }
    private MachineReport(boolean noInit) {}
    
    private static final MachineReport defaultInstance;
    public static MachineReport getDefaultInstance() {
      return defaultInstance;
    }
    
    public MachineReport getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReport_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReport_fieldAccessorTable;
    }
    
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      COMP_ID(0, 2000),
      MSG_TYPE(1, 61),
      ;
      
      public static final int COMP_ID_VALUE = 2000;
      public static final int MSG_TYPE_VALUE = 61;
      
      
      public final int getNumber() { return value; }
      
      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 61: return MSG_TYPE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CompType[] VALUES = {
        COMP_ID, MSG_TYPE, 
      };
      
      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.MachineReport.CompType)
    }
    
    // repeated .llsf_msgs.MachineReportEntry machines = 1;
    public static final int MACHINES_FIELD_NUMBER = 1;
    private java.util.List<org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry> machines_;
    public java.util.List<org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry> getMachinesList() {
      return machines_;
    }
    public java.util.List<? extends org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntryOrBuilder> 
        getMachinesOrBuilderList() {
      return machines_;
    }
    public int getMachinesCount() {
      return machines_.size();
    }
    public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry getMachines(int index) {
      return machines_.get(index);
    }
    public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntryOrBuilder getMachinesOrBuilder(
        int index) {
      return machines_.get(index);
    }
    
    private void initFields() {
      machines_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getMachinesCount(); i++) {
        if (!getMachines(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < machines_.size(); i++) {
        output.writeMessage(1, machines_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < machines_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, machines_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReport_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReport_fieldAccessorTable;
      }
      
      // Construct using org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMachinesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (machinesBuilder_ == null) {
          machines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          machinesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport.getDescriptor();
      }
      
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport.getDefaultInstance();
      }
      
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport build() {
        org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport buildPartial() {
        org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport result = new org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport(this);
        int from_bitField0_ = bitField0_;
        if (machinesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            machines_ = java.util.Collections.unmodifiableList(machines_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.machines_ = machines_;
        } else {
          result.machines_ = machinesBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport other) {
        if (other == org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport.getDefaultInstance()) return this;
        if (machinesBuilder_ == null) {
          if (!other.machines_.isEmpty()) {
            if (machines_.isEmpty()) {
              machines_ = other.machines_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMachinesIsMutable();
              machines_.addAll(other.machines_);
            }
            onChanged();
          }
        } else {
          if (!other.machines_.isEmpty()) {
            if (machinesBuilder_.isEmpty()) {
              machinesBuilder_.dispose();
              machinesBuilder_ = null;
              machines_ = other.machines_;
              bitField0_ = (bitField0_ & ~0x00000001);
              machinesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMachinesFieldBuilder() : null;
            } else {
              machinesBuilder_.addAllMessages(other.machines_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getMachinesCount(); i++) {
          if (!getMachines(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder subBuilder = org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMachines(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .llsf_msgs.MachineReportEntry machines = 1;
      private java.util.List<org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry> machines_ =
        java.util.Collections.emptyList();
      private void ensureMachinesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          machines_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry>(machines_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntryOrBuilder> machinesBuilder_;
      
      public java.util.List<org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry> getMachinesList() {
        if (machinesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(machines_);
        } else {
          return machinesBuilder_.getMessageList();
        }
      }
      public int getMachinesCount() {
        if (machinesBuilder_ == null) {
          return machines_.size();
        } else {
          return machinesBuilder_.getCount();
        }
      }
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry getMachines(int index) {
        if (machinesBuilder_ == null) {
          return machines_.get(index);
        } else {
          return machinesBuilder_.getMessage(index);
        }
      }
      public Builder setMachines(
          int index, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry value) {
        if (machinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMachinesIsMutable();
          machines_.set(index, value);
          onChanged();
        } else {
          machinesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMachines(
          int index, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder builderForValue) {
        if (machinesBuilder_ == null) {
          ensureMachinesIsMutable();
          machines_.set(index, builderForValue.build());
          onChanged();
        } else {
          machinesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMachines(org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry value) {
        if (machinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMachinesIsMutable();
          machines_.add(value);
          onChanged();
        } else {
          machinesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMachines(
          int index, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry value) {
        if (machinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMachinesIsMutable();
          machines_.add(index, value);
          onChanged();
        } else {
          machinesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMachines(
          org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder builderForValue) {
        if (machinesBuilder_ == null) {
          ensureMachinesIsMutable();
          machines_.add(builderForValue.build());
          onChanged();
        } else {
          machinesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMachines(
          int index, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder builderForValue) {
        if (machinesBuilder_ == null) {
          ensureMachinesIsMutable();
          machines_.add(index, builderForValue.build());
          onChanged();
        } else {
          machinesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMachines(
          java.lang.Iterable<? extends org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry> values) {
        if (machinesBuilder_ == null) {
          ensureMachinesIsMutable();
          super.addAll(values, machines_);
          onChanged();
        } else {
          machinesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMachines() {
        if (machinesBuilder_ == null) {
          machines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          machinesBuilder_.clear();
        }
        return this;
      }
      public Builder removeMachines(int index) {
        if (machinesBuilder_ == null) {
          ensureMachinesIsMutable();
          machines_.remove(index);
          onChanged();
        } else {
          machinesBuilder_.remove(index);
        }
        return this;
      }
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder getMachinesBuilder(
          int index) {
        return getMachinesFieldBuilder().getBuilder(index);
      }
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntryOrBuilder getMachinesOrBuilder(
          int index) {
        if (machinesBuilder_ == null) {
          return machines_.get(index);  } else {
          return machinesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntryOrBuilder> 
           getMachinesOrBuilderList() {
        if (machinesBuilder_ != null) {
          return machinesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(machines_);
        }
      }
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder addMachinesBuilder() {
        return getMachinesFieldBuilder().addBuilder(
            org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.getDefaultInstance());
      }
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder addMachinesBuilder(
          int index) {
        return getMachinesFieldBuilder().addBuilder(
            index, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.getDefaultInstance());
      }
      public java.util.List<org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder> 
           getMachinesBuilderList() {
        return getMachinesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntryOrBuilder> 
          getMachinesFieldBuilder() {
        if (machinesBuilder_ == null) {
          machinesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder, org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntryOrBuilder>(
                  machines_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          machines_ = null;
        }
        return machinesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:llsf_msgs.MachineReport)
    }
    
    static {
      defaultInstance = new MachineReport(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:llsf_msgs.MachineReport)
  }
  
  public interface MachineReportInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string reported_machines = 1;
    java.util.List<String> getReportedMachinesList();
    int getReportedMachinesCount();
    String getReportedMachines(int index);
  }
  public static final class MachineReportInfo extends
      com.google.protobuf.GeneratedMessage
      implements MachineReportInfoOrBuilder {
    // Use MachineReportInfo.newBuilder() to construct.
    private MachineReportInfo(Builder builder) {
      super(builder);
    }
    private MachineReportInfo(boolean noInit) {}
    
    private static final MachineReportInfo defaultInstance;
    public static MachineReportInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public MachineReportInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReportInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReportInfo_fieldAccessorTable;
    }
    
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      COMP_ID(0, 2000),
      MSG_TYPE(1, 62),
      ;
      
      public static final int COMP_ID_VALUE = 2000;
      public static final int MSG_TYPE_VALUE = 62;
      
      
      public final int getNumber() { return value; }
      
      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 62: return MSG_TYPE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CompType[] VALUES = {
        COMP_ID, MSG_TYPE, 
      };
      
      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.MachineReportInfo.CompType)
    }
    
    // repeated string reported_machines = 1;
    public static final int REPORTED_MACHINES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList reportedMachines_;
    public java.util.List<String>
        getReportedMachinesList() {
      return reportedMachines_;
    }
    public int getReportedMachinesCount() {
      return reportedMachines_.size();
    }
    public String getReportedMachines(int index) {
      return reportedMachines_.get(index);
    }
    
    private void initFields() {
      reportedMachines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < reportedMachines_.size(); i++) {
        output.writeBytes(1, reportedMachines_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < reportedMachines_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(reportedMachines_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getReportedMachinesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReportInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.internal_static_llsf_msgs_MachineReportInfo_fieldAccessorTable;
      }
      
      // Construct using org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        reportedMachines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo.getDescriptor();
      }
      
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo.getDefaultInstance();
      }
      
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo build() {
        org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo buildPartial() {
        org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo result = new org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          reportedMachines_ = new com.google.protobuf.UnmodifiableLazyStringList(
              reportedMachines_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.reportedMachines_ = reportedMachines_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo other) {
        if (other == org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo.getDefaultInstance()) return this;
        if (!other.reportedMachines_.isEmpty()) {
          if (reportedMachines_.isEmpty()) {
            reportedMachines_ = other.reportedMachines_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureReportedMachinesIsMutable();
            reportedMachines_.addAll(other.reportedMachines_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureReportedMachinesIsMutable();
              reportedMachines_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string reported_machines = 1;
      private com.google.protobuf.LazyStringList reportedMachines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureReportedMachinesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          reportedMachines_ = new com.google.protobuf.LazyStringArrayList(reportedMachines_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getReportedMachinesList() {
        return java.util.Collections.unmodifiableList(reportedMachines_);
      }
      public int getReportedMachinesCount() {
        return reportedMachines_.size();
      }
      public String getReportedMachines(int index) {
        return reportedMachines_.get(index);
      }
      public Builder setReportedMachines(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReportedMachinesIsMutable();
        reportedMachines_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addReportedMachines(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureReportedMachinesIsMutable();
        reportedMachines_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllReportedMachines(
          java.lang.Iterable<String> values) {
        ensureReportedMachinesIsMutable();
        super.addAll(values, reportedMachines_);
        onChanged();
        return this;
      }
      public Builder clearReportedMachines() {
        reportedMachines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addReportedMachines(com.google.protobuf.ByteString value) {
        ensureReportedMachinesIsMutable();
        reportedMachines_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:llsf_msgs.MachineReportInfo)
    }
    
    static {
      defaultInstance = new MachineReportInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:llsf_msgs.MachineReportInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_MachineReportEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_MachineReportEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_MachineReport_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_MachineReport_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_MachineReportInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_MachineReportInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MachineReport.proto\022\tllsf_msgs\032\021Machin" +
      "eInfo.proto\032\016PuckInfo.proto\"X\n\022MachineRe" +
      "portEntry\022\014\n\004name\030\001 \002(\t\022\014\n\004type\030\002 \002(\t\"&\n" +
      "\010CompType\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYPE\020<\"h\n" +
      "\rMachineReport\022/\n\010machines\030\001 \003(\0132\035.llsf_" +
      "msgs.MachineReportEntry\"&\n\010CompType\022\014\n\007C" +
      "OMP_ID\020\320\017\022\014\n\010MSG_TYPE\020=\"V\n\021MachineReport" +
      "Info\022\031\n\021reported_machines\030\001 \003(\t\"&\n\010CompT" +
      "ype\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYPE\020>B6\n\037org.r" +
      "obocup_logistics.llsf_msgsB\023MachineRepor",
      "tProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_llsf_msgs_MachineReportEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_llsf_msgs_MachineReportEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_MachineReportEntry_descriptor,
              new java.lang.String[] { "Name", "Type", },
              org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.class,
              org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportEntry.Builder.class);
          internal_static_llsf_msgs_MachineReport_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_llsf_msgs_MachineReport_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_MachineReport_descriptor,
              new java.lang.String[] { "Machines", },
              org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport.class,
              org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReport.Builder.class);
          internal_static_llsf_msgs_MachineReportInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_llsf_msgs_MachineReportInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_MachineReportInfo_descriptor,
              new java.lang.String[] { "ReportedMachines", },
              org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo.class,
              org.robocup_logistics.llsf_msgs.MachineReportProtos.MachineReportInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robocup_logistics.llsf_msgs.MachineInfoProtos.getDescriptor(),
          org.robocup_logistics.llsf_msgs.PuckInfoProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
