// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderInfo.proto

package org.robocup_logistics.llsf_msgs;

public final class OrderInfoProtos {
  private OrderInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OrderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 id = 1;
    boolean hasId();
    int getId();
    
    // required .llsf_msgs.Order.ProductType product = 2;
    boolean hasProduct();
    org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType getProduct();
    
    // required uint32 quantity_requested = 3;
    boolean hasQuantityRequested();
    int getQuantityRequested();
    
    // required uint32 quantity_delivered = 4;
    boolean hasQuantityDelivered();
    int getQuantityDelivered();
    
    // required uint32 delivery_period_begin = 6;
    boolean hasDeliveryPeriodBegin();
    int getDeliveryPeriodBegin();
    
    // required uint32 delivery_period_end = 7;
    boolean hasDeliveryPeriodEnd();
    int getDeliveryPeriodEnd();
    
    // optional .llsf_msgs.Order.DeliveryGate delivery_gate = 8 [default = ANY];
    boolean hasDeliveryGate();
    org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate getDeliveryGate();
  }
  public static final class Order extends
      com.google.protobuf.GeneratedMessage
      implements OrderOrBuilder {
    // Use Order.newBuilder() to construct.
    private Order(Builder builder) {
      super(builder);
    }
    private Order(boolean noInit) {}
    
    private static final Order defaultInstance;
    public static Order getDefaultInstance() {
      return defaultInstance;
    }
    
    public Order getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.OrderInfoProtos.internal_static_llsf_msgs_Order_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.OrderInfoProtos.internal_static_llsf_msgs_Order_fieldAccessorTable;
    }
    
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      COMP_ID(0, 2000),
      MSG_TYPE(1, 40),
      ;
      
      public static final int COMP_ID_VALUE = 2000;
      public static final int MSG_TYPE_VALUE = 40;
      
      
      public final int getNumber() { return value; }
      
      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 40: return MSG_TYPE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CompType[] VALUES = {
        COMP_ID, MSG_TYPE, 
      };
      
      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.Order.CompType)
    }
    
    public enum ProductType
        implements com.google.protobuf.ProtocolMessageEnum {
      P1(0, 1),
      P2(1, 2),
      P3(2, 3),
      ;
      
      public static final int P1_VALUE = 1;
      public static final int P2_VALUE = 2;
      public static final int P3_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static ProductType valueOf(int value) {
        switch (value) {
          case 1: return P1;
          case 2: return P2;
          case 3: return P3;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ProductType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ProductType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ProductType>() {
              public ProductType findValueByNumber(int number) {
                return ProductType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final ProductType[] VALUES = {
        P1, P2, P3, 
      };
      
      public static ProductType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private ProductType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.Order.ProductType)
    }
    
    public enum DeliveryGate
        implements com.google.protobuf.ProtocolMessageEnum {
      ANY(0, 1),
      D1(1, 2),
      D2(2, 3),
      D3(3, 4),
      ;
      
      public static final int ANY_VALUE = 1;
      public static final int D1_VALUE = 2;
      public static final int D2_VALUE = 3;
      public static final int D3_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static DeliveryGate valueOf(int value) {
        switch (value) {
          case 1: return ANY;
          case 2: return D1;
          case 3: return D2;
          case 4: return D3;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<DeliveryGate>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DeliveryGate>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DeliveryGate>() {
              public DeliveryGate findValueByNumber(int number) {
                return DeliveryGate.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.getDescriptor().getEnumTypes().get(2);
      }
      
      private static final DeliveryGate[] VALUES = {
        ANY, D1, D2, D3, 
      };
      
      public static DeliveryGate valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private DeliveryGate(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.Order.DeliveryGate)
    }
    
    private int bitField0_;
    // required uint32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required .llsf_msgs.Order.ProductType product = 2;
    public static final int PRODUCT_FIELD_NUMBER = 2;
    private org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType product_;
    public boolean hasProduct() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType getProduct() {
      return product_;
    }
    
    // required uint32 quantity_requested = 3;
    public static final int QUANTITY_REQUESTED_FIELD_NUMBER = 3;
    private int quantityRequested_;
    public boolean hasQuantityRequested() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getQuantityRequested() {
      return quantityRequested_;
    }
    
    // required uint32 quantity_delivered = 4;
    public static final int QUANTITY_DELIVERED_FIELD_NUMBER = 4;
    private int quantityDelivered_;
    public boolean hasQuantityDelivered() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getQuantityDelivered() {
      return quantityDelivered_;
    }
    
    // required uint32 delivery_period_begin = 6;
    public static final int DELIVERY_PERIOD_BEGIN_FIELD_NUMBER = 6;
    private int deliveryPeriodBegin_;
    public boolean hasDeliveryPeriodBegin() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getDeliveryPeriodBegin() {
      return deliveryPeriodBegin_;
    }
    
    // required uint32 delivery_period_end = 7;
    public static final int DELIVERY_PERIOD_END_FIELD_NUMBER = 7;
    private int deliveryPeriodEnd_;
    public boolean hasDeliveryPeriodEnd() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getDeliveryPeriodEnd() {
      return deliveryPeriodEnd_;
    }
    
    // optional .llsf_msgs.Order.DeliveryGate delivery_gate = 8 [default = ANY];
    public static final int DELIVERY_GATE_FIELD_NUMBER = 8;
    private org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate deliveryGate_;
    public boolean hasDeliveryGate() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate getDeliveryGate() {
      return deliveryGate_;
    }
    
    private void initFields() {
      id_ = 0;
      product_ = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType.P1;
      quantityRequested_ = 0;
      quantityDelivered_ = 0;
      deliveryPeriodBegin_ = 0;
      deliveryPeriodEnd_ = 0;
      deliveryGate_ = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate.ANY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProduct()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuantityRequested()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuantityDelivered()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeliveryPeriodBegin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeliveryPeriodEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, product_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, quantityRequested_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, quantityDelivered_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(6, deliveryPeriodBegin_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(7, deliveryPeriodEnd_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(8, deliveryGate_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, product_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, quantityRequested_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, quantityDelivered_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, deliveryPeriodBegin_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, deliveryPeriodEnd_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, deliveryGate_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.internal_static_llsf_msgs_Order_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.internal_static_llsf_msgs_Order_fieldAccessorTable;
      }
      
      // Construct using org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        product_ = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType.P1;
        bitField0_ = (bitField0_ & ~0x00000002);
        quantityRequested_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        quantityDelivered_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        deliveryPeriodBegin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        deliveryPeriodEnd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        deliveryGate_ = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate.ANY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.getDescriptor();
      }
      
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.getDefaultInstance();
      }
      
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order build() {
        org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order buildPartial() {
        org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order result = new org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.product_ = product_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.quantityRequested_ = quantityRequested_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.quantityDelivered_ = quantityDelivered_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deliveryPeriodBegin_ = deliveryPeriodBegin_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.deliveryPeriodEnd_ = deliveryPeriodEnd_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.deliveryGate_ = deliveryGate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order other) {
        if (other == org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasProduct()) {
          setProduct(other.getProduct());
        }
        if (other.hasQuantityRequested()) {
          setQuantityRequested(other.getQuantityRequested());
        }
        if (other.hasQuantityDelivered()) {
          setQuantityDelivered(other.getQuantityDelivered());
        }
        if (other.hasDeliveryPeriodBegin()) {
          setDeliveryPeriodBegin(other.getDeliveryPeriodBegin());
        }
        if (other.hasDeliveryPeriodEnd()) {
          setDeliveryPeriodEnd(other.getDeliveryPeriodEnd());
        }
        if (other.hasDeliveryGate()) {
          setDeliveryGate(other.getDeliveryGate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasProduct()) {
          
          return false;
        }
        if (!hasQuantityRequested()) {
          
          return false;
        }
        if (!hasQuantityDelivered()) {
          
          return false;
        }
        if (!hasDeliveryPeriodBegin()) {
          
          return false;
        }
        if (!hasDeliveryPeriodEnd()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType value = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                product_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              quantityRequested_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              quantityDelivered_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              deliveryPeriodBegin_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              deliveryPeriodEnd_ = input.readUInt32();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate value = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                deliveryGate_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required .llsf_msgs.Order.ProductType product = 2;
      private org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType product_ = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType.P1;
      public boolean hasProduct() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType getProduct() {
        return product_;
      }
      public Builder setProduct(org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        product_ = value;
        onChanged();
        return this;
      }
      public Builder clearProduct() {
        bitField0_ = (bitField0_ & ~0x00000002);
        product_ = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.ProductType.P1;
        onChanged();
        return this;
      }
      
      // required uint32 quantity_requested = 3;
      private int quantityRequested_ ;
      public boolean hasQuantityRequested() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getQuantityRequested() {
        return quantityRequested_;
      }
      public Builder setQuantityRequested(int value) {
        bitField0_ |= 0x00000004;
        quantityRequested_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuantityRequested() {
        bitField0_ = (bitField0_ & ~0x00000004);
        quantityRequested_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 quantity_delivered = 4;
      private int quantityDelivered_ ;
      public boolean hasQuantityDelivered() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getQuantityDelivered() {
        return quantityDelivered_;
      }
      public Builder setQuantityDelivered(int value) {
        bitField0_ |= 0x00000008;
        quantityDelivered_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuantityDelivered() {
        bitField0_ = (bitField0_ & ~0x00000008);
        quantityDelivered_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 delivery_period_begin = 6;
      private int deliveryPeriodBegin_ ;
      public boolean hasDeliveryPeriodBegin() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getDeliveryPeriodBegin() {
        return deliveryPeriodBegin_;
      }
      public Builder setDeliveryPeriodBegin(int value) {
        bitField0_ |= 0x00000010;
        deliveryPeriodBegin_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeliveryPeriodBegin() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deliveryPeriodBegin_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 delivery_period_end = 7;
      private int deliveryPeriodEnd_ ;
      public boolean hasDeliveryPeriodEnd() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getDeliveryPeriodEnd() {
        return deliveryPeriodEnd_;
      }
      public Builder setDeliveryPeriodEnd(int value) {
        bitField0_ |= 0x00000020;
        deliveryPeriodEnd_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeliveryPeriodEnd() {
        bitField0_ = (bitField0_ & ~0x00000020);
        deliveryPeriodEnd_ = 0;
        onChanged();
        return this;
      }
      
      // optional .llsf_msgs.Order.DeliveryGate delivery_gate = 8 [default = ANY];
      private org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate deliveryGate_ = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate.ANY;
      public boolean hasDeliveryGate() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate getDeliveryGate() {
        return deliveryGate_;
      }
      public Builder setDeliveryGate(org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        deliveryGate_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeliveryGate() {
        bitField0_ = (bitField0_ & ~0x00000040);
        deliveryGate_ = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.DeliveryGate.ANY;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:llsf_msgs.Order)
    }
    
    static {
      defaultInstance = new Order(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:llsf_msgs.Order)
  }
  
  public interface OrderInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .llsf_msgs.Order orders = 1;
    java.util.List<org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order> 
        getOrdersList();
    org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order getOrders(int index);
    int getOrdersCount();
    java.util.List<? extends org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderOrBuilder> 
        getOrdersOrBuilderList();
    org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderOrBuilder getOrdersOrBuilder(
        int index);
  }
  public static final class OrderInfo extends
      com.google.protobuf.GeneratedMessage
      implements OrderInfoOrBuilder {
    // Use OrderInfo.newBuilder() to construct.
    private OrderInfo(Builder builder) {
      super(builder);
    }
    private OrderInfo(boolean noInit) {}
    
    private static final OrderInfo defaultInstance;
    public static OrderInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public OrderInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.OrderInfoProtos.internal_static_llsf_msgs_OrderInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.OrderInfoProtos.internal_static_llsf_msgs_OrderInfo_fieldAccessorTable;
    }
    
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      COMP_ID(0, 2000),
      MSG_TYPE(1, 41),
      ;
      
      public static final int COMP_ID_VALUE = 2000;
      public static final int MSG_TYPE_VALUE = 41;
      
      
      public final int getNumber() { return value; }
      
      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 41: return MSG_TYPE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CompType[] VALUES = {
        COMP_ID, MSG_TYPE, 
      };
      
      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.OrderInfo.CompType)
    }
    
    // repeated .llsf_msgs.Order orders = 1;
    public static final int ORDERS_FIELD_NUMBER = 1;
    private java.util.List<org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order> orders_;
    public java.util.List<org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order> getOrdersList() {
      return orders_;
    }
    public java.util.List<? extends org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderOrBuilder> 
        getOrdersOrBuilderList() {
      return orders_;
    }
    public int getOrdersCount() {
      return orders_.size();
    }
    public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order getOrders(int index) {
      return orders_.get(index);
    }
    public org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderOrBuilder getOrdersOrBuilder(
        int index) {
      return orders_.get(index);
    }
    
    private void initFields() {
      orders_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getOrdersCount(); i++) {
        if (!getOrders(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < orders_.size(); i++) {
        output.writeMessage(1, orders_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < orders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, orders_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.internal_static_llsf_msgs_OrderInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.internal_static_llsf_msgs_OrderInfo_fieldAccessorTable;
      }
      
      // Construct using org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOrdersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ordersBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo.getDescriptor();
      }
      
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo.getDefaultInstance();
      }
      
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo build() {
        org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo buildPartial() {
        org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo result = new org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo(this);
        int from_bitField0_ = bitField0_;
        if (ordersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            orders_ = java.util.Collections.unmodifiableList(orders_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.orders_ = orders_;
        } else {
          result.orders_ = ordersBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo other) {
        if (other == org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo.getDefaultInstance()) return this;
        if (ordersBuilder_ == null) {
          if (!other.orders_.isEmpty()) {
            if (orders_.isEmpty()) {
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOrdersIsMutable();
              orders_.addAll(other.orders_);
            }
            onChanged();
          }
        } else {
          if (!other.orders_.isEmpty()) {
            if (ordersBuilder_.isEmpty()) {
              ordersBuilder_.dispose();
              ordersBuilder_ = null;
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ordersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOrdersFieldBuilder() : null;
            } else {
              ordersBuilder_.addAllMessages(other.orders_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getOrdersCount(); i++) {
          if (!getOrders(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder subBuilder = org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOrders(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .llsf_msgs.Order orders = 1;
      private java.util.List<org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order> orders_ =
        java.util.Collections.emptyList();
      private void ensureOrdersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          orders_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order>(orders_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order, org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder, org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderOrBuilder> ordersBuilder_;
      
      public java.util.List<org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order> getOrdersList() {
        if (ordersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orders_);
        } else {
          return ordersBuilder_.getMessageList();
        }
      }
      public int getOrdersCount() {
        if (ordersBuilder_ == null) {
          return orders_.size();
        } else {
          return ordersBuilder_.getCount();
        }
      }
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order getOrders(int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);
        } else {
          return ordersBuilder_.getMessage(index);
        }
      }
      public Builder setOrders(
          int index, org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.set(index, value);
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setOrders(
          int index, org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.set(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addOrders(org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addOrders(
          int index, org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(index, value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addOrders(
          org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addOrders(
          int index, org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllOrders(
          java.lang.Iterable<? extends org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order> values) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          super.addAll(values, orders_);
          onChanged();
        } else {
          ordersBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearOrders() {
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ordersBuilder_.clear();
        }
        return this;
      }
      public Builder removeOrders(int index) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.remove(index);
          onChanged();
        } else {
          ordersBuilder_.remove(index);
        }
        return this;
      }
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder getOrdersBuilder(
          int index) {
        return getOrdersFieldBuilder().getBuilder(index);
      }
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderOrBuilder getOrdersOrBuilder(
          int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);  } else {
          return ordersBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderOrBuilder> 
           getOrdersOrBuilderList() {
        if (ordersBuilder_ != null) {
          return ordersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orders_);
        }
      }
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder addOrdersBuilder() {
        return getOrdersFieldBuilder().addBuilder(
            org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.getDefaultInstance());
      }
      public org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder addOrdersBuilder(
          int index) {
        return getOrdersFieldBuilder().addBuilder(
            index, org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.getDefaultInstance());
      }
      public java.util.List<org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder> 
           getOrdersBuilderList() {
        return getOrdersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order, org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder, org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderOrBuilder> 
          getOrdersFieldBuilder() {
        if (ordersBuilder_ == null) {
          ordersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order, org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder, org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderOrBuilder>(
                  orders_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          orders_ = null;
        }
        return ordersBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:llsf_msgs.OrderInfo)
    }
    
    static {
      defaultInstance = new OrderInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:llsf_msgs.OrderInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_Order_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_Order_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_OrderInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_OrderInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017OrderInfo.proto\022\tllsf_msgs\"\361\002\n\005Order\022\n" +
      "\n\002id\030\001 \002(\r\022-\n\007product\030\002 \002(\0162\034.llsf_msgs." +
      "Order.ProductType\022\032\n\022quantity_requested\030" +
      "\003 \002(\r\022\032\n\022quantity_delivered\030\004 \002(\r\022\035\n\025del" +
      "ivery_period_begin\030\006 \002(\r\022\033\n\023delivery_per" +
      "iod_end\030\007 \002(\r\0229\n\rdelivery_gate\030\010 \001(\0162\035.l" +
      "lsf_msgs.Order.DeliveryGate:\003ANY\"&\n\010Comp" +
      "Type\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYPE\020(\"%\n\013Prod" +
      "uctType\022\006\n\002P1\020\001\022\006\n\002P2\020\002\022\006\n\002P3\020\003\"/\n\014Deliv" +
      "eryGate\022\007\n\003ANY\020\001\022\006\n\002D1\020\002\022\006\n\002D2\020\003\022\006\n\002D3\020\004",
      "\"U\n\tOrderInfo\022 \n\006orders\030\001 \003(\0132\020.llsf_msg" +
      "s.Order\"&\n\010CompType\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG" +
      "_TYPE\020)B2\n\037org.robocup_logistics.llsf_ms" +
      "gsB\017OrderInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_llsf_msgs_Order_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_llsf_msgs_Order_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_Order_descriptor,
              new java.lang.String[] { "Id", "Product", "QuantityRequested", "QuantityDelivered", "DeliveryPeriodBegin", "DeliveryPeriodEnd", "DeliveryGate", },
              org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.class,
              org.robocup_logistics.llsf_msgs.OrderInfoProtos.Order.Builder.class);
          internal_static_llsf_msgs_OrderInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_llsf_msgs_OrderInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_OrderInfo_descriptor,
              new java.lang.String[] { "Orders", },
              org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo.class,
              org.robocup_logistics.llsf_msgs.OrderInfoProtos.OrderInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
