// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RingInfo.proto

package org.robocup_logistics.llsf_msgs;

public final class RingInfoProtos {
  private RingInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.Ring)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
     *
     * <pre>
     * Ring color this concerns
     * </pre>
     */
    boolean hasRingColor();
    /**
     * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
     *
     * <pre>
     * Ring color this concerns
     * </pre>
     */
    org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor getRingColor();

    /**
     * <code>required uint32 raw_material = 2;</code>
     *
     * <pre>
     * number of additional bases
     * required to produce this ring type
     * </pre>
     */
    boolean hasRawMaterial();
    /**
     * <code>required uint32 raw_material = 2;</code>
     *
     * <pre>
     * number of additional bases
     * required to produce this ring type
     * </pre>
     */
    int getRawMaterial();
  }
  /**
   * Protobuf type {@code llsf_msgs.Ring}
   */
  public static final class Ring extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.Ring)
      RingOrBuilder {
    // Use Ring.newBuilder() to construct.
    private Ring(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Ring(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Ring defaultInstance;
    public static Ring getDefaultInstance() {
      return defaultInstance;
    }

    public Ring getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Ring(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor value = org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                ringColor_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rawMaterial_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.RingInfoProtos.internal_static_llsf_msgs_Ring_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.RingInfoProtos.internal_static_llsf_msgs_Ring_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.class, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder.class);
    }

    public static com.google.protobuf.Parser<Ring> PARSER =
        new com.google.protobuf.AbstractParser<Ring>() {
      public Ring parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ring(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Ring> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RING_COLOR_FIELD_NUMBER = 1;
    private org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor ringColor_;
    /**
     * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
     *
     * <pre>
     * Ring color this concerns
     * </pre>
     */
    public boolean hasRingColor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
     *
     * <pre>
     * Ring color this concerns
     * </pre>
     */
    public org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor getRingColor() {
      return ringColor_;
    }

    public static final int RAW_MATERIAL_FIELD_NUMBER = 2;
    private int rawMaterial_;
    /**
     * <code>required uint32 raw_material = 2;</code>
     *
     * <pre>
     * number of additional bases
     * required to produce this ring type
     * </pre>
     */
    public boolean hasRawMaterial() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 raw_material = 2;</code>
     *
     * <pre>
     * number of additional bases
     * required to produce this ring type
     * </pre>
     */
    public int getRawMaterial() {
      return rawMaterial_;
    }

    private void initFields() {
      ringColor_ = org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor.RING_BLUE;
      rawMaterial_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRingColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRawMaterial()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, ringColor_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, rawMaterial_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, ringColor_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, rawMaterial_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.Ring}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.Ring)
        org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RingInfoProtos.internal_static_llsf_msgs_Ring_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.RingInfoProtos.internal_static_llsf_msgs_Ring_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.class, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ringColor_ = org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor.RING_BLUE;
        bitField0_ = (bitField0_ & ~0x00000001);
        rawMaterial_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.RingInfoProtos.internal_static_llsf_msgs_Ring_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring build() {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring buildPartial() {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring result = new org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ringColor_ = ringColor_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rawMaterial_ = rawMaterial_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring other) {
        if (other == org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.getDefaultInstance()) return this;
        if (other.hasRingColor()) {
          setRingColor(other.getRingColor());
        }
        if (other.hasRawMaterial()) {
          setRawMaterial(other.getRawMaterial());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRingColor()) {
          
          return false;
        }
        if (!hasRawMaterial()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor ringColor_ = org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor.RING_BLUE;
      /**
       * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
       *
       * <pre>
       * Ring color this concerns
       * </pre>
       */
      public boolean hasRingColor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
       *
       * <pre>
       * Ring color this concerns
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor getRingColor() {
        return ringColor_;
      }
      /**
       * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
       *
       * <pre>
       * Ring color this concerns
       * </pre>
       */
      public Builder setRingColor(org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        ringColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .llsf_msgs.RingColor ring_color = 1;</code>
       *
       * <pre>
       * Ring color this concerns
       * </pre>
       */
      public Builder clearRingColor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ringColor_ = org.robocup_logistics.llsf_msgs.ProductColorProtos.RingColor.RING_BLUE;
        onChanged();
        return this;
      }

      private int rawMaterial_ ;
      /**
       * <code>required uint32 raw_material = 2;</code>
       *
       * <pre>
       * number of additional bases
       * required to produce this ring type
       * </pre>
       */
      public boolean hasRawMaterial() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 raw_material = 2;</code>
       *
       * <pre>
       * number of additional bases
       * required to produce this ring type
       * </pre>
       */
      public int getRawMaterial() {
        return rawMaterial_;
      }
      /**
       * <code>required uint32 raw_material = 2;</code>
       *
       * <pre>
       * number of additional bases
       * required to produce this ring type
       * </pre>
       */
      public Builder setRawMaterial(int value) {
        bitField0_ |= 0x00000002;
        rawMaterial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 raw_material = 2;</code>
       *
       * <pre>
       * number of additional bases
       * required to produce this ring type
       * </pre>
       */
      public Builder clearRawMaterial() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rawMaterial_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:llsf_msgs.Ring)
    }

    static {
      defaultInstance = new Ring(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.Ring)
  }

  public interface RingInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.RingInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     *
     * <pre>
     * List of all known pucks
     * </pre>
     */
    java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> 
        getRingsList();
    /**
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     *
     * <pre>
     * List of all known pucks
     * </pre>
     */
    org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring getRings(int index);
    /**
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     *
     * <pre>
     * List of all known pucks
     * </pre>
     */
    int getRingsCount();
    /**
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     *
     * <pre>
     * List of all known pucks
     * </pre>
     */
    java.util.List<? extends org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder> 
        getRingsOrBuilderList();
    /**
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     *
     * <pre>
     * List of all known pucks
     * </pre>
     */
    org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder getRingsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code llsf_msgs.RingInfo}
   */
  public static final class RingInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.RingInfo)
      RingInfoOrBuilder {
    // Use RingInfo.newBuilder() to construct.
    private RingInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RingInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RingInfo defaultInstance;
    public static RingInfo getDefaultInstance() {
      return defaultInstance;
    }

    public RingInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RingInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                rings_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring>();
                mutable_bitField0_ |= 0x00000001;
              }
              rings_.add(input.readMessage(org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          rings_ = java.util.Collections.unmodifiableList(rings_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.RingInfoProtos.internal_static_llsf_msgs_RingInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.RingInfoProtos.internal_static_llsf_msgs_RingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.class, org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<RingInfo> PARSER =
        new com.google.protobuf.AbstractParser<RingInfo>() {
      public RingInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RingInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RingInfo> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code llsf_msgs.RingInfo.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 2000;</code>
       */
      COMP_ID(0, 2000),
      /**
       * <code>MSG_TYPE = 110;</code>
       */
      MSG_TYPE(1, 110),
      ;

      /**
       * <code>COMP_ID = 2000;</code>
       */
      public static final int COMP_ID_VALUE = 2000;
      /**
       * <code>MSG_TYPE = 110;</code>
       */
      public static final int MSG_TYPE_VALUE = 110;


      public final int getNumber() { return value; }

      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 110: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:llsf_msgs.RingInfo.CompType)
    }

    public static final int RINGS_FIELD_NUMBER = 1;
    private java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> rings_;
    /**
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     *
     * <pre>
     * List of all known pucks
     * </pre>
     */
    public java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> getRingsList() {
      return rings_;
    }
    /**
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     *
     * <pre>
     * List of all known pucks
     * </pre>
     */
    public java.util.List<? extends org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder> 
        getRingsOrBuilderList() {
      return rings_;
    }
    /**
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     *
     * <pre>
     * List of all known pucks
     * </pre>
     */
    public int getRingsCount() {
      return rings_.size();
    }
    /**
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     *
     * <pre>
     * List of all known pucks
     * </pre>
     */
    public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring getRings(int index) {
      return rings_.get(index);
    }
    /**
     * <code>repeated .llsf_msgs.Ring rings = 1;</code>
     *
     * <pre>
     * List of all known pucks
     * </pre>
     */
    public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder getRingsOrBuilder(
        int index) {
      return rings_.get(index);
    }

    private void initFields() {
      rings_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getRingsCount(); i++) {
        if (!getRings(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < rings_.size(); i++) {
        output.writeMessage(1, rings_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rings_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.RingInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.RingInfo)
        org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RingInfoProtos.internal_static_llsf_msgs_RingInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.RingInfoProtos.internal_static_llsf_msgs_RingInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.class, org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRingsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (ringsBuilder_ == null) {
          rings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ringsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.RingInfoProtos.internal_static_llsf_msgs_RingInfo_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo build() {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo buildPartial() {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo result = new org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo(this);
        int from_bitField0_ = bitField0_;
        if (ringsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            rings_ = java.util.Collections.unmodifiableList(rings_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rings_ = rings_;
        } else {
          result.rings_ = ringsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo other) {
        if (other == org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo.getDefaultInstance()) return this;
        if (ringsBuilder_ == null) {
          if (!other.rings_.isEmpty()) {
            if (rings_.isEmpty()) {
              rings_ = other.rings_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRingsIsMutable();
              rings_.addAll(other.rings_);
            }
            onChanged();
          }
        } else {
          if (!other.rings_.isEmpty()) {
            if (ringsBuilder_.isEmpty()) {
              ringsBuilder_.dispose();
              ringsBuilder_ = null;
              rings_ = other.rings_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ringsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRingsFieldBuilder() : null;
            } else {
              ringsBuilder_.addAllMessages(other.rings_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getRingsCount(); i++) {
          if (!getRings(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.RingInfoProtos.RingInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> rings_ =
        java.util.Collections.emptyList();
      private void ensureRingsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          rings_ = new java.util.ArrayList<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring>(rings_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder, org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder> ringsBuilder_;

      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> getRingsList() {
        if (ringsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rings_);
        } else {
          return ringsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public int getRingsCount() {
        if (ringsBuilder_ == null) {
          return rings_.size();
        } else {
          return ringsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring getRings(int index) {
        if (ringsBuilder_ == null) {
          return rings_.get(index);
        } else {
          return ringsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public Builder setRings(
          int index, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring value) {
        if (ringsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRingsIsMutable();
          rings_.set(index, value);
          onChanged();
        } else {
          ringsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public Builder setRings(
          int index, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder builderForValue) {
        if (ringsBuilder_ == null) {
          ensureRingsIsMutable();
          rings_.set(index, builderForValue.build());
          onChanged();
        } else {
          ringsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public Builder addRings(org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring value) {
        if (ringsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRingsIsMutable();
          rings_.add(value);
          onChanged();
        } else {
          ringsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public Builder addRings(
          int index, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring value) {
        if (ringsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRingsIsMutable();
          rings_.add(index, value);
          onChanged();
        } else {
          ringsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public Builder addRings(
          org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder builderForValue) {
        if (ringsBuilder_ == null) {
          ensureRingsIsMutable();
          rings_.add(builderForValue.build());
          onChanged();
        } else {
          ringsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public Builder addRings(
          int index, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder builderForValue) {
        if (ringsBuilder_ == null) {
          ensureRingsIsMutable();
          rings_.add(index, builderForValue.build());
          onChanged();
        } else {
          ringsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public Builder addAllRings(
          java.lang.Iterable<? extends org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring> values) {
        if (ringsBuilder_ == null) {
          ensureRingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rings_);
          onChanged();
        } else {
          ringsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public Builder clearRings() {
        if (ringsBuilder_ == null) {
          rings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ringsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public Builder removeRings(int index) {
        if (ringsBuilder_ == null) {
          ensureRingsIsMutable();
          rings_.remove(index);
          onChanged();
        } else {
          ringsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder getRingsBuilder(
          int index) {
        return getRingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder getRingsOrBuilder(
          int index) {
        if (ringsBuilder_ == null) {
          return rings_.get(index);  } else {
          return ringsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public java.util.List<? extends org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder> 
           getRingsOrBuilderList() {
        if (ringsBuilder_ != null) {
          return ringsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rings_);
        }
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder addRingsBuilder() {
        return getRingsFieldBuilder().addBuilder(
            org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.getDefaultInstance());
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder addRingsBuilder(
          int index) {
        return getRingsFieldBuilder().addBuilder(
            index, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.getDefaultInstance());
      }
      /**
       * <code>repeated .llsf_msgs.Ring rings = 1;</code>
       *
       * <pre>
       * List of all known pucks
       * </pre>
       */
      public java.util.List<org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder> 
           getRingsBuilderList() {
        return getRingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder, org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder> 
          getRingsFieldBuilder() {
        if (ringsBuilder_ == null) {
          ringsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring, org.robocup_logistics.llsf_msgs.RingInfoProtos.Ring.Builder, org.robocup_logistics.llsf_msgs.RingInfoProtos.RingOrBuilder>(
                  rings_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          rings_ = null;
        }
        return ringsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:llsf_msgs.RingInfo)
    }

    static {
      defaultInstance = new RingInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.RingInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_Ring_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_Ring_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_RingInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_RingInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016RingInfo.proto\022\tllsf_msgs\032\022ProductColo" +
      "r.proto\"F\n\004Ring\022(\n\nring_color\030\001 \002(\0162\024.ll" +
      "sf_msgs.RingColor\022\024\n\014raw_material\030\002 \002(\r\"" +
      "R\n\010RingInfo\022\036\n\005rings\030\001 \003(\0132\017.llsf_msgs.R" +
      "ing\"&\n\010CompType\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYP" +
      "E\020nB1\n\037org.robocup_logistics.llsf_msgsB\016" +
      "RingInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robocup_logistics.llsf_msgs.ProductColorProtos.getDescriptor(),
        }, assigner);
    internal_static_llsf_msgs_Ring_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_llsf_msgs_Ring_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_llsf_msgs_Ring_descriptor,
        new java.lang.String[] { "RingColor", "RawMaterial", });
    internal_static_llsf_msgs_RingInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_llsf_msgs_RingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_llsf_msgs_RingInfo_descriptor,
        new java.lang.String[] { "Rings", });
    org.robocup_logistics.llsf_msgs.ProductColorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
