// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotCommands.proto

package org.robocup_logistics.llsf_msgs;

public final class RobotCommandsProtos {
  private RobotCommandsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SetRobotMaintenanceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 robot_number = 1;
    boolean hasRobotNumber();
    int getRobotNumber();
    
    // required bool maintenance = 3;
    boolean hasMaintenance();
    boolean getMaintenance();
  }
  public static final class SetRobotMaintenance extends
      com.google.protobuf.GeneratedMessage
      implements SetRobotMaintenanceOrBuilder {
    // Use SetRobotMaintenance.newBuilder() to construct.
    private SetRobotMaintenance(Builder builder) {
      super(builder);
    }
    private SetRobotMaintenance(boolean noInit) {}
    
    private static final SetRobotMaintenance defaultInstance;
    public static SetRobotMaintenance getDefaultInstance() {
      return defaultInstance;
    }
    
    public SetRobotMaintenance getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.RobotCommandsProtos.internal_static_llsf_msgs_SetRobotMaintenance_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.RobotCommandsProtos.internal_static_llsf_msgs_SetRobotMaintenance_fieldAccessorTable;
    }
    
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      COMP_ID(0, 2000),
      MSG_TYPE(1, 91),
      ;
      
      public static final int COMP_ID_VALUE = 2000;
      public static final int MSG_TYPE_VALUE = 91;
      
      
      public final int getNumber() { return value; }
      
      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 91: return MSG_TYPE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CompType[] VALUES = {
        COMP_ID, MSG_TYPE, 
      };
      
      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:llsf_msgs.SetRobotMaintenance.CompType)
    }
    
    private int bitField0_;
    // required uint32 robot_number = 1;
    public static final int ROBOT_NUMBER_FIELD_NUMBER = 1;
    private int robotNumber_;
    public boolean hasRobotNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getRobotNumber() {
      return robotNumber_;
    }
    
    // required bool maintenance = 3;
    public static final int MAINTENANCE_FIELD_NUMBER = 3;
    private boolean maintenance_;
    public boolean hasMaintenance() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getMaintenance() {
      return maintenance_;
    }
    
    private void initFields() {
      robotNumber_ = 0;
      maintenance_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRobotNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMaintenance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, robotNumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(3, maintenance_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, robotNumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, maintenance_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RobotCommandsProtos.internal_static_llsf_msgs_SetRobotMaintenance_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.RobotCommandsProtos.internal_static_llsf_msgs_SetRobotMaintenance_fieldAccessorTable;
      }
      
      // Construct using org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        robotNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        maintenance_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.getDescriptor();
      }
      
      public org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.getDefaultInstance();
      }
      
      public org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance build() {
        org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance buildPartial() {
        org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance result = new org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.robotNumber_ = robotNumber_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.maintenance_ = maintenance_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance other) {
        if (other == org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.getDefaultInstance()) return this;
        if (other.hasRobotNumber()) {
          setRobotNumber(other.getRobotNumber());
        }
        if (other.hasMaintenance()) {
          setMaintenance(other.getMaintenance());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRobotNumber()) {
          
          return false;
        }
        if (!hasMaintenance()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              robotNumber_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              maintenance_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 robot_number = 1;
      private int robotNumber_ ;
      public boolean hasRobotNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRobotNumber() {
        return robotNumber_;
      }
      public Builder setRobotNumber(int value) {
        bitField0_ |= 0x00000001;
        robotNumber_ = value;
        onChanged();
        return this;
      }
      public Builder clearRobotNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        robotNumber_ = 0;
        onChanged();
        return this;
      }
      
      // required bool maintenance = 3;
      private boolean maintenance_ ;
      public boolean hasMaintenance() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getMaintenance() {
        return maintenance_;
      }
      public Builder setMaintenance(boolean value) {
        bitField0_ |= 0x00000002;
        maintenance_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaintenance() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maintenance_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:llsf_msgs.SetRobotMaintenance)
    }
    
    static {
      defaultInstance = new SetRobotMaintenance(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:llsf_msgs.SetRobotMaintenance)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_SetRobotMaintenance_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_SetRobotMaintenance_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023RobotCommands.proto\022\tllsf_msgs\"h\n\023SetR" +
      "obotMaintenance\022\024\n\014robot_number\030\001 \002(\r\022\023\n" +
      "\013maintenance\030\003 \002(\010\"&\n\010CompType\022\014\n\007COMP_I" +
      "D\020\320\017\022\014\n\010MSG_TYPE\020[B6\n\037org.robocup_logist" +
      "ics.llsf_msgsB\023RobotCommandsProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_llsf_msgs_SetRobotMaintenance_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_llsf_msgs_SetRobotMaintenance_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_llsf_msgs_SetRobotMaintenance_descriptor,
              new java.lang.String[] { "RobotNumber", "Maintenance", },
              org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.class,
              org.robocup_logistics.llsf_msgs.RobotCommandsProtos.SetRobotMaintenance.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
