// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimTimeSync.proto

package org.robocup_logistics.llsf_msgs;

public final class SimTimeSyncProtos {
  private SimTimeSyncProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SimTimeSyncOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.SimTimeSync)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .llsf_msgs.Time sim_time = 1;</code>
     */
    boolean hasSimTime();
    /**
     * <code>required .llsf_msgs.Time sim_time = 1;</code>
     */
    org.robocup_logistics.llsf_msgs.TimeProtos.Time getSimTime();
    /**
     * <code>required .llsf_msgs.Time sim_time = 1;</code>
     */
    org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder getSimTimeOrBuilder();

    /**
     * <code>required float real_time_factor = 2;</code>
     */
    boolean hasRealTimeFactor();
    /**
     * <code>required float real_time_factor = 2;</code>
     */
    float getRealTimeFactor();

    /**
     * <code>required bool paused = 3;</code>
     */
    boolean hasPaused();
    /**
     * <code>required bool paused = 3;</code>
     */
    boolean getPaused();
  }
  /**
   * Protobuf type {@code llsf_msgs.SimTimeSync}
   */
  public static final class SimTimeSync extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.SimTimeSync)
      SimTimeSyncOrBuilder {
    // Use SimTimeSync.newBuilder() to construct.
    private SimTimeSync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SimTimeSync(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SimTimeSync defaultInstance;
    public static SimTimeSync getDefaultInstance() {
      return defaultInstance;
    }

    public SimTimeSync getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SimTimeSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = simTime_.toBuilder();
              }
              simTime_ = input.readMessage(org.robocup_logistics.llsf_msgs.TimeProtos.Time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simTime_);
                simTime_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              realTimeFactor_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              paused_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.internal_static_llsf_msgs_SimTimeSync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.internal_static_llsf_msgs_SimTimeSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync.class, org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync.Builder.class);
    }

    public static com.google.protobuf.Parser<SimTimeSync> PARSER =
        new com.google.protobuf.AbstractParser<SimTimeSync>() {
      public SimTimeSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimTimeSync(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SimTimeSync> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code llsf_msgs.SimTimeSync.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 2000;</code>
       */
      COMP_ID(0, 2000),
      /**
       * <code>MSG_TYPE = 327;</code>
       */
      MSG_TYPE(1, 327),
      ;

      /**
       * <code>COMP_ID = 2000;</code>
       */
      public static final int COMP_ID_VALUE = 2000;
      /**
       * <code>MSG_TYPE = 327;</code>
       */
      public static final int MSG_TYPE_VALUE = 327;


      public final int getNumber() { return value; }

      public static CompType valueOf(int value) {
        switch (value) {
          case 2000: return COMP_ID;
          case 327: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:llsf_msgs.SimTimeSync.CompType)
    }

    private int bitField0_;
    public static final int SIM_TIME_FIELD_NUMBER = 1;
    private org.robocup_logistics.llsf_msgs.TimeProtos.Time simTime_;
    /**
     * <code>required .llsf_msgs.Time sim_time = 1;</code>
     */
    public boolean hasSimTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .llsf_msgs.Time sim_time = 1;</code>
     */
    public org.robocup_logistics.llsf_msgs.TimeProtos.Time getSimTime() {
      return simTime_;
    }
    /**
     * <code>required .llsf_msgs.Time sim_time = 1;</code>
     */
    public org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder getSimTimeOrBuilder() {
      return simTime_;
    }

    public static final int REAL_TIME_FACTOR_FIELD_NUMBER = 2;
    private float realTimeFactor_;
    /**
     * <code>required float real_time_factor = 2;</code>
     */
    public boolean hasRealTimeFactor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float real_time_factor = 2;</code>
     */
    public float getRealTimeFactor() {
      return realTimeFactor_;
    }

    public static final int PAUSED_FIELD_NUMBER = 3;
    private boolean paused_;
    /**
     * <code>required bool paused = 3;</code>
     */
    public boolean hasPaused() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool paused = 3;</code>
     */
    public boolean getPaused() {
      return paused_;
    }

    private void initFields() {
      simTime_ = org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance();
      realTimeFactor_ = 0F;
      paused_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSimTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRealTimeFactor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPaused()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSimTime().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, simTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, realTimeFactor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, paused_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, simTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, realTimeFactor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, paused_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.SimTimeSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.SimTimeSync)
        org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.internal_static_llsf_msgs_SimTimeSync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.internal_static_llsf_msgs_SimTimeSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync.class, org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSimTimeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (simTimeBuilder_ == null) {
          simTime_ = org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance();
        } else {
          simTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        realTimeFactor_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        paused_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.internal_static_llsf_msgs_SimTimeSync_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync build() {
        org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync buildPartial() {
        org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync result = new org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (simTimeBuilder_ == null) {
          result.simTime_ = simTime_;
        } else {
          result.simTime_ = simTimeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.realTimeFactor_ = realTimeFactor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.paused_ = paused_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync other) {
        if (other == org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync.getDefaultInstance()) return this;
        if (other.hasSimTime()) {
          mergeSimTime(other.getSimTime());
        }
        if (other.hasRealTimeFactor()) {
          setRealTimeFactor(other.getRealTimeFactor());
        }
        if (other.hasPaused()) {
          setPaused(other.getPaused());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSimTime()) {
          
          return false;
        }
        if (!hasRealTimeFactor()) {
          
          return false;
        }
        if (!hasPaused()) {
          
          return false;
        }
        if (!getSimTime().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.SimTimeSyncProtos.SimTimeSync) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.robocup_logistics.llsf_msgs.TimeProtos.Time simTime_ = org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.robocup_logistics.llsf_msgs.TimeProtos.Time, org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder, org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder> simTimeBuilder_;
      /**
       * <code>required .llsf_msgs.Time sim_time = 1;</code>
       */
      public boolean hasSimTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .llsf_msgs.Time sim_time = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.TimeProtos.Time getSimTime() {
        if (simTimeBuilder_ == null) {
          return simTime_;
        } else {
          return simTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .llsf_msgs.Time sim_time = 1;</code>
       */
      public Builder setSimTime(org.robocup_logistics.llsf_msgs.TimeProtos.Time value) {
        if (simTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simTime_ = value;
          onChanged();
        } else {
          simTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .llsf_msgs.Time sim_time = 1;</code>
       */
      public Builder setSimTime(
          org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder builderForValue) {
        if (simTimeBuilder_ == null) {
          simTime_ = builderForValue.build();
          onChanged();
        } else {
          simTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .llsf_msgs.Time sim_time = 1;</code>
       */
      public Builder mergeSimTime(org.robocup_logistics.llsf_msgs.TimeProtos.Time value) {
        if (simTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              simTime_ != org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance()) {
            simTime_ =
              org.robocup_logistics.llsf_msgs.TimeProtos.Time.newBuilder(simTime_).mergeFrom(value).buildPartial();
          } else {
            simTime_ = value;
          }
          onChanged();
        } else {
          simTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .llsf_msgs.Time sim_time = 1;</code>
       */
      public Builder clearSimTime() {
        if (simTimeBuilder_ == null) {
          simTime_ = org.robocup_logistics.llsf_msgs.TimeProtos.Time.getDefaultInstance();
          onChanged();
        } else {
          simTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .llsf_msgs.Time sim_time = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder getSimTimeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSimTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>required .llsf_msgs.Time sim_time = 1;</code>
       */
      public org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder getSimTimeOrBuilder() {
        if (simTimeBuilder_ != null) {
          return simTimeBuilder_.getMessageOrBuilder();
        } else {
          return simTime_;
        }
      }
      /**
       * <code>required .llsf_msgs.Time sim_time = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.robocup_logistics.llsf_msgs.TimeProtos.Time, org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder, org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder> 
          getSimTimeFieldBuilder() {
        if (simTimeBuilder_ == null) {
          simTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.robocup_logistics.llsf_msgs.TimeProtos.Time, org.robocup_logistics.llsf_msgs.TimeProtos.Time.Builder, org.robocup_logistics.llsf_msgs.TimeProtos.TimeOrBuilder>(
                  getSimTime(),
                  getParentForChildren(),
                  isClean());
          simTime_ = null;
        }
        return simTimeBuilder_;
      }

      private float realTimeFactor_ ;
      /**
       * <code>required float real_time_factor = 2;</code>
       */
      public boolean hasRealTimeFactor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float real_time_factor = 2;</code>
       */
      public float getRealTimeFactor() {
        return realTimeFactor_;
      }
      /**
       * <code>required float real_time_factor = 2;</code>
       */
      public Builder setRealTimeFactor(float value) {
        bitField0_ |= 0x00000002;
        realTimeFactor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float real_time_factor = 2;</code>
       */
      public Builder clearRealTimeFactor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        realTimeFactor_ = 0F;
        onChanged();
        return this;
      }

      private boolean paused_ ;
      /**
       * <code>required bool paused = 3;</code>
       */
      public boolean hasPaused() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool paused = 3;</code>
       */
      public boolean getPaused() {
        return paused_;
      }
      /**
       * <code>required bool paused = 3;</code>
       */
      public Builder setPaused(boolean value) {
        bitField0_ |= 0x00000004;
        paused_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool paused = 3;</code>
       */
      public Builder clearPaused() {
        bitField0_ = (bitField0_ & ~0x00000004);
        paused_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:llsf_msgs.SimTimeSync)
    }

    static {
      defaultInstance = new SimTimeSync(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.SimTimeSync)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_SimTimeSync_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_SimTimeSync_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021SimTimeSync.proto\022\tllsf_msgs\032\nTime.pro" +
      "to\"\203\001\n\013SimTimeSync\022!\n\010sim_time\030\001 \002(\0132\017.l" +
      "lsf_msgs.Time\022\030\n\020real_time_factor\030\002 \002(\002\022" +
      "\016\n\006paused\030\003 \002(\010\"\'\n\010CompType\022\014\n\007COMP_ID\020\320" +
      "\017\022\r\n\010MSG_TYPE\020\307\002B4\n\037org.robocup_logistic" +
      "s.llsf_msgsB\021SimTimeSyncProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robocup_logistics.llsf_msgs.TimeProtos.getDescriptor(),
        }, assigner);
    internal_static_llsf_msgs_SimTimeSync_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_llsf_msgs_SimTimeSync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_llsf_msgs_SimTimeSync_descriptor,
        new java.lang.String[] { "SimTime", "RealTimeFactor", "Paused", });
    org.robocup_logistics.llsf_msgs.TimeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
