// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Zone.proto

package org.robocup_logistics.llsf_msgs;

public final class ZoneProtos {
  private ZoneProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code llsf_msgs.Zone}
   *
   * <pre>
   * Zone identifiers
   * </pre>
   */
  public enum Zone
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Z1 = 1;</code>
     */
    Z1(0, 1),
    /**
     * <code>Z2 = 2;</code>
     */
    Z2(1, 2),
    /**
     * <code>Z3 = 3;</code>
     */
    Z3(2, 3),
    /**
     * <code>Z4 = 4;</code>
     */
    Z4(3, 4),
    /**
     * <code>Z5 = 5;</code>
     */
    Z5(4, 5),
    /**
     * <code>Z6 = 6;</code>
     */
    Z6(5, 6),
    /**
     * <code>Z7 = 7;</code>
     */
    Z7(6, 7),
    /**
     * <code>Z8 = 8;</code>
     */
    Z8(7, 8),
    /**
     * <code>Z9 = 9;</code>
     */
    Z9(8, 9),
    /**
     * <code>Z10 = 10;</code>
     */
    Z10(9, 10),
    /**
     * <code>Z11 = 11;</code>
     */
    Z11(10, 11),
    /**
     * <code>Z12 = 12;</code>
     */
    Z12(11, 12),
    /**
     * <code>Z13 = 13;</code>
     */
    Z13(12, 13),
    /**
     * <code>Z14 = 14;</code>
     */
    Z14(13, 14),
    /**
     * <code>Z15 = 15;</code>
     */
    Z15(14, 15),
    /**
     * <code>Z16 = 16;</code>
     */
    Z16(15, 16),
    /**
     * <code>Z17 = 17;</code>
     */
    Z17(16, 17),
    /**
     * <code>Z18 = 18;</code>
     */
    Z18(17, 18),
    /**
     * <code>Z19 = 19;</code>
     */
    Z19(18, 19),
    /**
     * <code>Z20 = 20;</code>
     */
    Z20(19, 20),
    /**
     * <code>Z21 = 21;</code>
     */
    Z21(20, 21),
    /**
     * <code>Z22 = 22;</code>
     */
    Z22(21, 22),
    /**
     * <code>Z23 = 23;</code>
     */
    Z23(22, 23),
    /**
     * <code>Z24 = 24;</code>
     */
    Z24(23, 24),
    ;

    /**
     * <code>Z1 = 1;</code>
     */
    public static final int Z1_VALUE = 1;
    /**
     * <code>Z2 = 2;</code>
     */
    public static final int Z2_VALUE = 2;
    /**
     * <code>Z3 = 3;</code>
     */
    public static final int Z3_VALUE = 3;
    /**
     * <code>Z4 = 4;</code>
     */
    public static final int Z4_VALUE = 4;
    /**
     * <code>Z5 = 5;</code>
     */
    public static final int Z5_VALUE = 5;
    /**
     * <code>Z6 = 6;</code>
     */
    public static final int Z6_VALUE = 6;
    /**
     * <code>Z7 = 7;</code>
     */
    public static final int Z7_VALUE = 7;
    /**
     * <code>Z8 = 8;</code>
     */
    public static final int Z8_VALUE = 8;
    /**
     * <code>Z9 = 9;</code>
     */
    public static final int Z9_VALUE = 9;
    /**
     * <code>Z10 = 10;</code>
     */
    public static final int Z10_VALUE = 10;
    /**
     * <code>Z11 = 11;</code>
     */
    public static final int Z11_VALUE = 11;
    /**
     * <code>Z12 = 12;</code>
     */
    public static final int Z12_VALUE = 12;
    /**
     * <code>Z13 = 13;</code>
     */
    public static final int Z13_VALUE = 13;
    /**
     * <code>Z14 = 14;</code>
     */
    public static final int Z14_VALUE = 14;
    /**
     * <code>Z15 = 15;</code>
     */
    public static final int Z15_VALUE = 15;
    /**
     * <code>Z16 = 16;</code>
     */
    public static final int Z16_VALUE = 16;
    /**
     * <code>Z17 = 17;</code>
     */
    public static final int Z17_VALUE = 17;
    /**
     * <code>Z18 = 18;</code>
     */
    public static final int Z18_VALUE = 18;
    /**
     * <code>Z19 = 19;</code>
     */
    public static final int Z19_VALUE = 19;
    /**
     * <code>Z20 = 20;</code>
     */
    public static final int Z20_VALUE = 20;
    /**
     * <code>Z21 = 21;</code>
     */
    public static final int Z21_VALUE = 21;
    /**
     * <code>Z22 = 22;</code>
     */
    public static final int Z22_VALUE = 22;
    /**
     * <code>Z23 = 23;</code>
     */
    public static final int Z23_VALUE = 23;
    /**
     * <code>Z24 = 24;</code>
     */
    public static final int Z24_VALUE = 24;


    public final int getNumber() { return value; }

    public static Zone valueOf(int value) {
      switch (value) {
        case 1: return Z1;
        case 2: return Z2;
        case 3: return Z3;
        case 4: return Z4;
        case 5: return Z5;
        case 6: return Z6;
        case 7: return Z7;
        case 8: return Z8;
        case 9: return Z9;
        case 10: return Z10;
        case 11: return Z11;
        case 12: return Z12;
        case 13: return Z13;
        case 14: return Z14;
        case 15: return Z15;
        case 16: return Z16;
        case 17: return Z17;
        case 18: return Z18;
        case 19: return Z19;
        case 20: return Z20;
        case 21: return Z21;
        case 22: return Z22;
        case 23: return Z23;
        case 24: return Z24;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Zone>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Zone>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Zone>() {
            public Zone findValueByNumber(int number) {
              return Zone.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.ZoneProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final Zone[] VALUES = values();

    public static Zone valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Zone(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llsf_msgs.Zone)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nZone.proto\022\tllsf_msgs*\325\001\n\004Zone\022\006\n\002Z1\020\001" +
      "\022\006\n\002Z2\020\002\022\006\n\002Z3\020\003\022\006\n\002Z4\020\004\022\006\n\002Z5\020\005\022\006\n\002Z6\020\006" +
      "\022\006\n\002Z7\020\007\022\006\n\002Z8\020\010\022\006\n\002Z9\020\t\022\007\n\003Z10\020\n\022\007\n\003Z11" +
      "\020\013\022\007\n\003Z12\020\014\022\007\n\003Z13\020\r\022\007\n\003Z14\020\016\022\007\n\003Z15\020\017\022\007" +
      "\n\003Z16\020\020\022\007\n\003Z17\020\021\022\007\n\003Z18\020\022\022\007\n\003Z19\020\023\022\007\n\003Z2" +
      "0\020\024\022\007\n\003Z21\020\025\022\007\n\003Z22\020\026\022\007\n\003Z23\020\027\022\007\n\003Z24\020\030B" +
      "-\n\037org.robocup_logistics.llsf_msgsB\nZone" +
      "Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
